---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Kept in sync with the lowest Java version Jenkins can run on
      - dependency-name: "eclipse-temurin"
