name: ci
 
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
 
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          tags: jenkins/core-pr-tester:latest
